# Generated by Django 4.0.4 on 2022-06-27 05:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_product_available_alter_product_created_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0003_cart_productcart_delete_orderitems_cart_productcart_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='enable',
            field=models.BooleanField(default=True, verbose_name='enable'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='productcart',
            field=models.ManyToManyField(through='orders.ProductCart', to='home.product', verbose_name='productcart'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usertocart', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='productcart',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartrelations', to='orders.cart', verbose_name='cart'),
        ),
        migrations.AlterField(
            model_name='productcart',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productrelations', to='home.product', verbose_name='product'),
        ),
        migrations.AlterField(
            model_name='productcart',
            name='quantity',
            field=models.IntegerField(verbose_name='quantity'),
        ),
    ]
